In [7]:
import numpy as np #导入NumPy
X = np.array(5) # 创建0D张量，也就是标量
print("X的值",X)
print("X的阶",X.ndim) #ndim属性显示张量轴的个数
print("X的数据类型",X.dtype) # dtype属性显示张量数据类型
print("X的形状",X.shape) # shape属性显示张量形状

X的值 5
X的阶 0
X的数据类型 int64
X的形状 ()


In [22]:
n = 0
for gender in [0,1]:
    n = n + 1 # Python要求4个空格表示语句块缩进


In [21]:
print(n)

2


In [9]:
X = np.array([5,6,7,8,9]) #创建1D张量，也就是向量
print("X的值",X)
print("X的阶",X.ndim) #ndim属性显示张量轴的个数
print("X的形状",X.shape) # shape属性显示张量形状

X的值 [5 6 7 8 9]
X的阶 1
X的形状 (5,)


In [10]:
X = np.array([5]) # 1维的向量，就是1D数组里面只有一个元素

In [11]:
from keras.datasets import boston_housing # 波士顿房价数据集
#(X_train, y_train), (X_test, y_test) = boston_housing.load_data()
data = np.load('/Users/mollytsai/电子资源-零基础学机器学习/第1课 机器学习实战/练习用例 波士顿房价预测/代码/boston_housing.npz')

# 提取训练集和测试集
X_train = data['x']
y_train = data['y']
X_test = data['x']
y_test = data['y']

In [26]:
X_train

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [29]:
print("X_train的形状：", X_train.shape)
print("X_train中第一个样本的形状：", X_train[0].shape)
print("y_train的形状：", y_train.shape)

X_train的形状： (506, 13)
X_train中第一个样本的形状： (13,)
y_train的形状： (506,)


In [28]:
y_train

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [13]:
weight = np.array([1,-1.8,1,1,2]) # 权重向量(也就是多项式的参数)
X = np.array([1,6,7,8,9]) # 特征向量(也就是一个特定样本中的特征值)
y_hat = np.dot(X,weight) # 通过点积运算构建预测函数
print('函数返回结果:', y_hat) # 输出预测结果

函数返回结果: 23.2


In [14]:
y_hat = weight.dot(X) # X.dot(weight)也可以实现同样结果

In [15]:
print("X_train的内容：", X_train) #X_train是2D张量，即矩阵

X_train的内容： [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [16]:
# 创建3D张量
X = np.array([[[1, 22, 4, 78, 2],
               [2, 59, 6, 56, 1],
               [3, 31, 8, 54, 0]],
              [[4, 56, 9, 34, 1],
               [5, 78, 8, 35, 2],
               [6, 34, 7, 36, 0]],
              [[7, 45,5, 34, 5],
               [8, 53, 6, 35, 4],
               [9, 81, 4, 36, 5]]])